spring:
  application:
    name: catalogue-vigacat
  profiles:
    active: local

server:
  port: 8082
  servlet:
    context-path: /catalogue

logging:
  level:
    root: info

vigacat:
  security:
    url: http://localhost:8081
  app:
    name: Catalogue