INSERT INTO genre (genre)
VALUES ('First-Person Shooter'),
       ('Action'),
       ('MMO'),
       ('Survival Horror'),
       ('Stealth Action'),
       ('Historical Simulation'),
       ('Sports Simulation'),
       ('Point-and-Click'),
       ('Psychological Horror'),
       ('Battle Royale'),
       ('Life Simulation'),
       ('Dungeon Crawler'),
       ('Tactical RPG'),
       ('Real-Time Tactics'),
       ('Card Battler'),
       ('Space Exploration'),
       ('Time Travel'),
       ('Alternate History'),
       ('Monster Capture'),
       ('Mech Simulation'),
       ('Sandbox RPG'),
       ('Narrative Adventure'),
       ('Surreal'),
       ('Historical Strategy'),
       ('City Building'),
       ('Detective'),
       ('Monster Hunting'),
       ('Real-Time Strategy'),
       ('Space Opera'),
       ('Superhero'),
       ('Interactive Movie'),
       ('Educational Simulation'),
       ('Tower Defense'),
       ('4X Strategy'),
       ('Post-Apocalyptic RPG'),
       ('Mythology'),
       ('Wild West'),
       ('Espionage'),
       ('Trading Card Game'),
       ('Political Simulation'),
       ('Mythical Creatures'),
       ('Battle Arena'),
       ('Open World'),
       ('Roguelike'),
       ('Battle Card'),
       ('Farming Simulation'),
       ('Zombie'),
       ('Dynamic Sandbox'),
       ('Urban Fantasy'),
       ('Conspiracy'),
       ('God Game'),
       ('Sailing'),
       ('Business Simulation'),
       ('Hacking'),
       ('Martial Arts'),
       ('Superpowers'),
       ('Pirate'),
       ('Wildlife Simulation'),
       ('Apocalyptic'),
       ('Alternate Universe'),
       ('Creature Collecting'),
       ('Realistic Fiction');

-- REVERT
-- DELETE FROM genre
-- WHERE name IN (
-- 'First-Person Shooter',
-- 'Action',
-- 'MMO',
-- 'Survival Horror',
-- 'Stealth Action',
-- 'Historical Simulation',
-- 'Sports Simulation',
-- 'Point-and-Click',
-- 'Psychological Horror',
-- 'Battle Royale',
-- 'Life Simulation',
-- 'Dungeon Crawler',
-- 'Tactical RPG',
-- 'Real-Time Tactics',
-- 'Card Battler',
-- 'Space Exploration',
-- 'Time Travel',
-- 'Alternate History',
-- 'Monster Capture',
-- 'Mech Simulation',
-- 'Sandbox RPG',
-- 'Narrative Adventure',
-- 'Surreal',
-- 'Historical Strategy',
-- 'City Building',
-- 'Detective',
-- 'Monster Hunting',
-- 'Real-Time Strategy',
-- 'Space Opera',
-- 'Superhero',
-- 'Interactive Movie',
-- 'Educational Simulation',
-- 'Tower Defense',
-- '4X Strategy',
-- 'Post-Apocalyptic RPG',
-- 'Mythology',
-- 'Wild West',
-- 'Espionage',
-- 'Trading Card Game',
-- 'Political Simulation',
-- 'Mythical Creatures',
-- 'Battle Arena',
-- 'Open World',
-- 'Roguelike',
-- 'Battle Card',
-- 'Farming Simulation',
-- 'Zombie',
-- 'Dynamic Sandbox',
-- 'Urban Fantasy',
-- 'Conspiracy',
-- 'God Game',
-- 'Sailing',
-- 'Business Simulation',
-- 'Hacking',
-- 'Martial Arts',
-- 'Superpowers',
-- 'Pirate',
-- 'Wildlife Simulation',
-- 'Apocalyptic',
-- 'Alternate Universe',
-- 'Creature Collecting',
-- 'Realistic Fiction');
-- DELETE FROM flyway_schema_history WHERE version = '1.5';